name: Docker Build

on:
  push:
      branches: [ "main" ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: "cloud-native-godefroy"
      ACTOR: "mellimoy01"
      
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      
    - name: Build the image
      run: docker build -t ${{ env.REGISTRY }}/${{ env.ACTOR}}/${{ env.IMAGE_NAME}}/back:1.0.0 .
      working-directory: cloud-native-epsi/back
      
    - name: Login to GitHub Container Registery
      uses: Docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
          context: back
          push: true
          tags: ${{ env.REGISTRY}}/${{env.ACTOR}}/${{env.IMAGE_NAME}}/back:1.0.0
