name: Docker Build

on:
  push:
      branches: [ "main" ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t back .
      working-directory: cloud-native-epsi/back
    - run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS}} ghcr.io
